// adding a product
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

// getting the products
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS'
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO'
export const OBTENER_PRODUCTOS_ERROR = 'OBTENER_PRODUCTOS_ERROR'

// deleting the products
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO'
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR'
